// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package sqlitestore

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, token_hash, labels, status, last_seen_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	TokenHash  string         `json:"token_hash"`
	Labels     string         `json:"labels"`
	Status     string         `json:"status"`
	LastSeenAt sql.NullString `json:"last_seen_at"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.Labels,
		arg.Status,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, token_hash, labels, status, last_seen_at, created_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgentByID(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, name, token_hash, labels, status, last_seen_at, created_at FROM agents WHERE name = ?
`

func (q *Queries) GetAgentByName(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByName, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, token_hash, labels, status, last_seen_at, created_at FROM agents ORDER BY created_at DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = ?, last_seen_at = ? WHERE id = ?
`

type UpdateAgentStatusParams struct {
	Status     string         `json:"status"`
	LastSeenAt sql.NullString `json:"last_seen_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentStatus, arg.Status, arg.LastSeenAt, arg.ID)
	return err
}
