// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitestore

import (
	"database/sql"
)

type Agent struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	TokenHash  string         `json:"token_hash"`
	Labels     string         `json:"labels"`
	Status     string         `json:"status"`
	LastSeenAt sql.NullString `json:"last_seen_at"`
	CreatedAt  string         `json:"created_at"`
}
