// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: previews.sql

package sqlitestore

import (
	"context"
	"database/sql"
)

const getPreviewByID = `-- name: GetPreviewByID :one
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, public_url, labels, error_message, created_at, updated_at FROM previews WHERE id = ?
`

func (q *Queries) GetPreviewByID(ctx context.Context, id string) (Preview, error) {
	row := q.db.QueryRowContext(ctx, getPreviewByID, id)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.PublicUrl,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreviewByRepoAndPR = `-- name: GetPreviewByRepoAndPR :one
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, public_url, labels, error_message, created_at, updated_at FROM previews WHERE repo_full_name = ? AND pr_number = ?
`

type GetPreviewByRepoAndPRParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int64  `json:"pr_number"`
}

func (q *Queries) GetPreviewByRepoAndPR(ctx context.Context, arg GetPreviewByRepoAndPRParams) (Preview, error) {
	row := q.db.QueryRowContext(ctx, getPreviewByRepoAndPR, arg.RepoFullName, arg.PrNumber)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.PublicUrl,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPreviewEvent = `-- name: InsertPreviewEvent :exec
INSERT INTO preview_events (id, preview_id, from_status, to_status, message, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPreviewEventParams struct {
	ID         string         `json:"id"`
	PreviewID  string         `json:"preview_id"`
	FromStatus sql.NullString `json:"from_status"`
	ToStatus   string         `json:"to_status"`
	Message    string         `json:"message"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) InsertPreviewEvent(ctx context.Context, arg InsertPreviewEventParams) error {
	_, err := q.db.ExecContext(ctx, insertPreviewEvent,
		arg.ID,
		arg.PreviewID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const listAllPreviews = `-- name: ListAllPreviews :many
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, public_url, labels, error_message, created_at, updated_at FROM previews ORDER BY created_at DESC
`

func (q *Queries) ListAllPreviews(ctx context.Context) ([]Preview, error) {
	rows, err := q.db.QueryContext(ctx, listAllPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.AssignedAgentID,
			&i.ContainerID,
			&i.AgentHost,
			&i.AgentPort,
			&i.PublicUrl,
			&i.Labels,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreviewStatus = `-- name: UpdatePreviewStatus :exec
UPDATE previews
SET status = ?, error_message = ?, updated_at = ?
WHERE id = ?
`

type UpdatePreviewStatusParams struct {
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdatePreviewStatus(ctx context.Context, arg UpdatePreviewStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePreviewStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertPreview = `-- name: UpsertPreview :one
INSERT INTO previews (
  id, repo_full_name, pr_number, commit_sha, branch,
  status, labels, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, 'queued', ?, ?, ?)
ON CONFLICT(repo_full_name, pr_number) DO UPDATE SET
  commit_sha = EXCLUDED.commit_sha,
  branch = EXCLUDED.branch,
  labels = EXCLUDED.labels,
  updated_at = EXCLUDED.updated_at
RETURNING id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, public_url, labels, error_message, created_at, updated_at
`

type UpsertPreviewParams struct {
	ID           string `json:"id"`
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int64  `json:"pr_number"`
	CommitSha    string `json:"commit_sha"`
	Branch       string `json:"branch"`
	Labels       string `json:"labels"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) UpsertPreview(ctx context.Context, arg UpsertPreviewParams) (Preview, error) {
	row := q.db.QueryRowContext(ctx, upsertPreview,
		arg.ID,
		arg.RepoFullName,
		arg.PrNumber,
		arg.CommitSha,
		arg.Branch,
		arg.Labels,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.PublicUrl,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
