// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: previews.sql

package sqlitestore

import (
	"context"
	"database/sql"
	"strings"
)

const claimPreview = `-- name: ClaimPreview :one
UPDATE previews
SET status = 'assigned',
    assigned_agent_id = ?,
    updated_at = ?
WHERE id = (
  SELECT p.id FROM previews p
  WHERE p.status = 'queued'
    AND p.id IN (/*SLICE:candidate_ids*/?)
  ORDER BY p.created_at ASC
  LIMIT 1
)
RETURNING id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc
`

type ClaimPreviewParams struct {
	AssignedAgentID sql.NullString `json:"assigned_agent_id"`
	UpdatedAt       string         `json:"updated_at"`
	CandidateIds    []string       `json:"candidate_ids"`
}

func (q *Queries) ClaimPreview(ctx context.Context, arg ClaimPreviewParams) (Preview, error) {
	query := claimPreview
	var queryParams []interface{}
	queryParams = append(queryParams, arg.AssignedAgentID)
	queryParams = append(queryParams, arg.UpdatedAt)
	if len(arg.CandidateIds) > 0 {
		for _, v := range arg.CandidateIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:candidate_ids*/?", strings.Repeat(",?", len(arg.CandidateIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:candidate_ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoCloneUrl,
		&i.PreviewUrls,
		&i.IsAdhoc,
	)
	return i, err
}

const findPreviewByHost = `-- name: FindPreviewByHost :one
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews WHERE pr_number = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) FindPreviewByHost(ctx context.Context, prNumber int64) (Preview, error) {
	row := q.db.QueryRowContext(ctx, findPreviewByHost, prNumber)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoCloneUrl,
		&i.PreviewUrls,
		&i.IsAdhoc,
	)
	return i, err
}

const getActivePreviewByRepoAndPR = `-- name: GetActivePreviewByRepoAndPR :one
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews
WHERE repo_full_name = ? AND pr_number = ?
  AND status IN ('queued','assigned','building','running')
ORDER BY created_at DESC
LIMIT 1
`

type GetActivePreviewByRepoAndPRParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int64  `json:"pr_number"`
}

func (q *Queries) GetActivePreviewByRepoAndPR(ctx context.Context, arg GetActivePreviewByRepoAndPRParams) (Preview, error) {
	row := q.db.QueryRowContext(ctx, getActivePreviewByRepoAndPR, arg.RepoFullName, arg.PrNumber)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoCloneUrl,
		&i.PreviewUrls,
		&i.IsAdhoc,
	)
	return i, err
}

const getPreviewByID = `-- name: GetPreviewByID :one
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews WHERE id = ?
`

func (q *Queries) GetPreviewByID(ctx context.Context, id string) (Preview, error) {
	row := q.db.QueryRowContext(ctx, getPreviewByID, id)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoCloneUrl,
		&i.PreviewUrls,
		&i.IsAdhoc,
	)
	return i, err
}

const getPreviewByRepoAndPR = `-- name: GetPreviewByRepoAndPR :one
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews WHERE repo_full_name = ? AND pr_number = ?
`

type GetPreviewByRepoAndPRParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int64  `json:"pr_number"`
}

func (q *Queries) GetPreviewByRepoAndPR(ctx context.Context, arg GetPreviewByRepoAndPRParams) (Preview, error) {
	row := q.db.QueryRowContext(ctx, getPreviewByRepoAndPR, arg.RepoFullName, arg.PrNumber)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoCloneUrl,
		&i.PreviewUrls,
		&i.IsAdhoc,
	)
	return i, err
}

const getPreviewByRepoAndSha = `-- name: GetPreviewByRepoAndSha :one
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews WHERE repo_full_name = ? AND commit_sha = ?
`

type GetPreviewByRepoAndShaParams struct {
	RepoFullName string         `json:"repo_full_name"`
	CommitSha    sql.NullString `json:"commit_sha"`
}

func (q *Queries) GetPreviewByRepoAndSha(ctx context.Context, arg GetPreviewByRepoAndShaParams) (Preview, error) {
	row := q.db.QueryRowContext(ctx, getPreviewByRepoAndSha, arg.RepoFullName, arg.CommitSha)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoCloneUrl,
		&i.PreviewUrls,
		&i.IsAdhoc,
	)
	return i, err
}

const insertPreviewEvent = `-- name: InsertPreviewEvent :exec
INSERT INTO preview_events (id, preview_id, from_status, to_status, message, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPreviewEventParams struct {
	ID         string         `json:"id"`
	PreviewID  string         `json:"preview_id"`
	FromStatus sql.NullString `json:"from_status"`
	ToStatus   string         `json:"to_status"`
	Message    string         `json:"message"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) InsertPreviewEvent(ctx context.Context, arg InsertPreviewEventParams) error {
	_, err := q.db.ExecContext(ctx, insertPreviewEvent,
		arg.ID,
		arg.PreviewID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const listAllPreviews = `-- name: ListAllPreviews :many
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews ORDER BY created_at DESC
`

func (q *Queries) ListAllPreviews(ctx context.Context) ([]Preview, error) {
	rows, err := q.db.QueryContext(ctx, listAllPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.AssignedAgentID,
			&i.ContainerID,
			&i.AgentHost,
			&i.AgentPort,
			&i.Labels,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoCloneUrl,
			&i.PreviewUrls,
			&i.IsAdhoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByAgent = `-- name: ListByAgent :many
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews
WHERE assigned_agent_id = ?
  AND status IN (/*SLICE:statuses*/?)
ORDER BY updated_at ASC
`

type ListByAgentParams struct {
	AssignedAgentID sql.NullString `json:"assigned_agent_id"`
	Statuses        []string       `json:"statuses"`
}

func (q *Queries) ListByAgent(ctx context.Context, arg ListByAgentParams) ([]Preview, error) {
	query := listByAgent
	var queryParams []interface{}
	queryParams = append(queryParams, arg.AssignedAgentID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.AssignedAgentID,
			&i.ContainerID,
			&i.AgentHost,
			&i.AgentPort,
			&i.Labels,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoCloneUrl,
			&i.PreviewUrls,
			&i.IsAdhoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewEvents = `-- name: ListPreviewEvents :many
SELECT id, preview_id, from_status, to_status, message, created_at FROM preview_events
WHERE preview_id = ?
ORDER BY created_at ASC, id ASC
LIMIT ? OFFSET ?
`

type ListPreviewEventsParams struct {
	PreviewID string `json:"preview_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListPreviewEvents(ctx context.Context, arg ListPreviewEventsParams) ([]PreviewEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPreviewEvents, arg.PreviewID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PreviewEvent{}
	for rows.Next() {
		var i PreviewEvent
		if err := rows.Scan(
			&i.ID,
			&i.PreviewID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewRepos = `-- name: ListPreviewRepos :many
SELECT DISTINCT repo_full_name
FROM previews
ORDER BY repo_full_name
`

func (q *Queries) ListPreviewRepos(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPreviewRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var repo_full_name string
		if err := rows.Scan(&repo_full_name); err != nil {
			return nil, err
		}
		items = append(items, repo_full_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedPreviewsForLabels = `-- name: ListQueuedPreviewsForLabels :many
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews WHERE status = 'queued' ORDER BY created_at ASC LIMIT 50
`

func (q *Queries) ListQueuedPreviewsForLabels(ctx context.Context) ([]Preview, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedPreviewsForLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.AssignedAgentID,
			&i.ContainerID,
			&i.AgentHost,
			&i.AgentPort,
			&i.Labels,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoCloneUrl,
			&i.PreviewUrls,
			&i.IsAdhoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningPreviewsByAgent = `-- name: ListRunningPreviewsByAgent :many
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews WHERE status = 'running' AND assigned_agent_id = ? ORDER BY updated_at ASC
`

func (q *Queries) ListRunningPreviewsByAgent(ctx context.Context, assignedAgentID sql.NullString) ([]Preview, error) {
	rows, err := q.db.QueryContext(ctx, listRunningPreviewsByAgent, assignedAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.AssignedAgentID,
			&i.ContainerID,
			&i.AgentHost,
			&i.AgentPort,
			&i.Labels,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoCloneUrl,
			&i.PreviewUrls,
			&i.IsAdhoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAssignedPreviews = `-- name: ListStaleAssignedPreviews :many
SELECT id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc FROM previews WHERE status = 'assigned' AND updated_at < ? ORDER BY updated_at ASC
`

func (q *Queries) ListStaleAssignedPreviews(ctx context.Context, updatedAt string) ([]Preview, error) {
	rows, err := q.db.QueryContext(ctx, listStaleAssignedPreviews, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.AssignedAgentID,
			&i.ContainerID,
			&i.AgentHost,
			&i.AgentPort,
			&i.Labels,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoCloneUrl,
			&i.PreviewUrls,
			&i.IsAdhoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllAssignedPreviews = `-- name: ResetAllAssignedPreviews :execrows
UPDATE previews SET status = 'queued', assigned_agent_id = NULL, updated_at = ? WHERE status = 'assigned'
`

func (q *Queries) ResetAllAssignedPreviews(ctx context.Context, updatedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetAllAssignedPreviews, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePreviewStatus = `-- name: UpdatePreviewStatus :exec
UPDATE previews
SET status = ?, error_message = ?, updated_at = ?
WHERE id = ?
`

type UpdatePreviewStatusParams struct {
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdatePreviewStatus(ctx context.Context, arg UpdatePreviewStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePreviewStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updatePreviewStatusFields = `-- name: UpdatePreviewStatusFields :execrows
UPDATE previews
SET status = ?,
    updated_at = ?,
    container_id = COALESCE(?, container_id),
    agent_host = COALESCE(?, agent_host),
    agent_port = COALESCE(?, agent_port),
    preview_urls = COALESCE(?, preview_urls),
    error_message = COALESCE(?, error_message),
    assigned_agent_id = COALESCE(?, assigned_agent_id),
    commit_sha = COALESCE(commit_sha, ?)
WHERE id = ?
`

type UpdatePreviewStatusFieldsParams struct {
	Status          string         `json:"status"`
	UpdatedAt       string         `json:"updated_at"`
	ContainerID     sql.NullString `json:"container_id"`
	AgentHost       sql.NullString `json:"agent_host"`
	AgentPort       sql.NullInt64  `json:"agent_port"`
	PreviewUrls     string         `json:"preview_urls"`
	ErrorMessage    sql.NullString `json:"error_message"`
	AssignedAgentID sql.NullString `json:"assigned_agent_id"`
	CommitSha       sql.NullString `json:"commit_sha"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdatePreviewStatusFields(ctx context.Context, arg UpdatePreviewStatusFieldsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePreviewStatusFields,
		arg.Status,
		arg.UpdatedAt,
		arg.ContainerID,
		arg.AgentHost,
		arg.AgentPort,
		arg.PreviewUrls,
		arg.ErrorMessage,
		arg.AssignedAgentID,
		arg.CommitSha,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPreview = `-- name: UpsertPreview :one
INSERT INTO previews (
  id, repo_full_name, pr_number, commit_sha, branch,
  status, labels, repo_clone_url, is_adhoc, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, 'queued', ?, ?, ?, ?, ?)
ON CONFLICT(repo_full_name, commit_sha) DO UPDATE SET
  pr_number = EXCLUDED.pr_number,
  branch = EXCLUDED.branch,
  labels = EXCLUDED.labels,
  repo_clone_url = EXCLUDED.repo_clone_url,
  updated_at = EXCLUDED.updated_at
RETURNING id, repo_full_name, pr_number, commit_sha, branch, status, assigned_agent_id, container_id, agent_host, agent_port, labels, error_message, created_at, updated_at, repo_clone_url, preview_urls, is_adhoc
`

type UpsertPreviewParams struct {
	ID           string         `json:"id"`
	RepoFullName string         `json:"repo_full_name"`
	PrNumber     int64          `json:"pr_number"`
	CommitSha    sql.NullString `json:"commit_sha"`
	Branch       string         `json:"branch"`
	Labels       string         `json:"labels"`
	RepoCloneUrl string         `json:"repo_clone_url"`
	IsAdhoc      int64          `json:"is_adhoc"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) UpsertPreview(ctx context.Context, arg UpsertPreviewParams) (Preview, error) {
	row := q.db.QueryRowContext(ctx, upsertPreview,
		arg.ID,
		arg.RepoFullName,
		arg.PrNumber,
		arg.CommitSha,
		arg.Branch,
		arg.Labels,
		arg.RepoCloneUrl,
		arg.IsAdhoc,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.AssignedAgentID,
		&i.ContainerID,
		&i.AgentHost,
		&i.AgentPort,
		&i.Labels,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoCloneUrl,
		&i.PreviewUrls,
		&i.IsAdhoc,
	)
	return i, err
}
