// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitestore

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClaimPreview(ctx context.Context, arg ClaimPreviewParams) (Preview, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) error
	DeleteAgent(ctx context.Context, id string) error
	DeleteAllRepoSecretsFor(ctx context.Context, repoFullName string) error
	DeleteRepoSecret(ctx context.Context, arg DeleteRepoSecretParams) error
	FindPreviewByHost(ctx context.Context, prNumber int64) (Preview, error)
	GetActivePreviewByRepoAndPR(ctx context.Context, arg GetActivePreviewByRepoAndPRParams) (Preview, error)
	GetAgentByID(ctx context.Context, id string) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetPreviewByID(ctx context.Context, id string) (Preview, error)
	GetPreviewByRepoAndPR(ctx context.Context, arg GetPreviewByRepoAndPRParams) (Preview, error)
	GetPreviewByRepoAndSha(ctx context.Context, arg GetPreviewByRepoAndShaParams) (Preview, error)
	InsertPreviewEvent(ctx context.Context, arg InsertPreviewEventParams) error
	ListAgents(ctx context.Context) ([]Agent, error)
	ListAllPreviews(ctx context.Context) ([]Preview, error)
	ListByAgent(ctx context.Context, arg ListByAgentParams) ([]Preview, error)
	ListPreviewEvents(ctx context.Context, arg ListPreviewEventsParams) ([]PreviewEvent, error)
	ListPreviewRepos(ctx context.Context) ([]string, error)
	ListQueuedPreviewsForLabels(ctx context.Context) ([]Preview, error)
	ListRepoSecretRepos(ctx context.Context) ([]string, error)
	ListRepoSecrets(ctx context.Context, repoFullName string) ([]RepoSecret, error)
	ListRunningPreviewsByAgent(ctx context.Context, assignedAgentID sql.NullString) ([]Preview, error)
	ListStaleAssignedPreviews(ctx context.Context, updatedAt string) ([]Preview, error)
	ResetAllAssignedPreviews(ctx context.Context, updatedAt string) (int64, error)
	ResetAllOnlineAgents(ctx context.Context) (int64, error)
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error
	UpdatePreviewStatus(ctx context.Context, arg UpdatePreviewStatusParams) error
	UpdatePreviewStatusFields(ctx context.Context, arg UpdatePreviewStatusFieldsParams) (int64, error)
	UpsertPreview(ctx context.Context, arg UpsertPreviewParams) (Preview, error)
	UpsertRepoSecret(ctx context.Context, arg UpsertRepoSecretParams) error
}

var _ Querier = (*Queries)(nil)
