// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitestore

import (
	"context"
)

type Querier interface {
	CreateAgent(ctx context.Context, arg CreateAgentParams) error
	DeleteAgent(ctx context.Context, id string) error
	GetAgentByID(ctx context.Context, id string) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error
}

var _ Querier = (*Queries)(nil)
