// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repo_secrets.sql

package sqlitestore

import (
	"context"
)

const deleteAllRepoSecretsFor = `-- name: DeleteAllRepoSecretsFor :exec
DELETE FROM repo_secrets WHERE repo_full_name = ?
`

func (q *Queries) DeleteAllRepoSecretsFor(ctx context.Context, repoFullName string) error {
	_, err := q.db.ExecContext(ctx, deleteAllRepoSecretsFor, repoFullName)
	return err
}

const deleteRepoSecret = `-- name: DeleteRepoSecret :exec
DELETE FROM repo_secrets WHERE repo_full_name = ? AND key = ?
`

type DeleteRepoSecretParams struct {
	RepoFullName string `json:"repo_full_name"`
	Key          string `json:"key"`
}

func (q *Queries) DeleteRepoSecret(ctx context.Context, arg DeleteRepoSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteRepoSecret, arg.RepoFullName, arg.Key)
	return err
}

const listRepoSecretRepos = `-- name: ListRepoSecretRepos :many
SELECT DISTINCT repo_full_name
FROM repo_secrets
ORDER BY repo_full_name
`

func (q *Queries) ListRepoSecretRepos(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRepoSecretRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var repo_full_name string
		if err := rows.Scan(&repo_full_name); err != nil {
			return nil, err
		}
		items = append(items, repo_full_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoSecrets = `-- name: ListRepoSecrets :many
SELECT repo_full_name, key, value, updated_at
FROM repo_secrets
WHERE repo_full_name = ?
ORDER BY key
`

func (q *Queries) ListRepoSecrets(ctx context.Context, repoFullName string) ([]RepoSecret, error) {
	rows, err := q.db.QueryContext(ctx, listRepoSecrets, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoSecret{}
	for rows.Next() {
		var i RepoSecret
		if err := rows.Scan(
			&i.RepoFullName,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepoSecret = `-- name: UpsertRepoSecret :exec
INSERT INTO repo_secrets (repo_full_name, key, value, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(repo_full_name, key) DO UPDATE SET
    value      = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertRepoSecretParams struct {
	RepoFullName string `json:"repo_full_name"`
	Key          string `json:"key"`
	Value        string `json:"value"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) UpsertRepoSecret(ctx context.Context, arg UpsertRepoSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepoSecret,
		arg.RepoFullName,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}
